USE_CAMERA_STUB := true

# inherit from common msm8660 device
-include device/htc/msm8660-common/BoardConfigCommon.mk

# inherit from the proprietary version
-include vendor/htc/shooter/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true

TARGET_BOOTLOADER_BOARD_NAME := shooter
TARGET_NO_RADIOIMAGE := true

# TARGET_SPECIFIC_HEADER_PATH := device/htc/shooter/include
TARGET_SPECIFIC_HEADER_PATH := device/htc/msm8660-common/include

# Gps
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := shooter

TARGET_HARDWARE_3D := true
TARGET_SLIMER_CAM := true

TARGET_USE_SCORPION_BIONIC_OPTIMIZATION := true

# BOARD_HAVE_SQN_WIMAX := true

BOARD_KERNEL_CMDLINE := no_console_suspend=1
BOARD_KERNEL_BASE := 0x48000000
BOARD_PAGE_SIZE := 2048

# Define Prebuilt kernel locations
TARGET_PREBUILT_KERNEL := device/htc/shooter/prebuilt/root/kernel

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16776192
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 838860800
BOARD_USERDATAIMAGE_PARTITION_SIZE := 20044333056
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_RELEASETOOLS_EXTENSIONS := device/htc/common

BOARD_SDCARD_DEVICE_PRIMARY := /dev/block/mmcblk1p1
BOARD_SDCARD_DEVICE_SECONDARY := /dev/block/mmcblk1
BOARD_SDEXT_DEVICE := /dev/block/mmcblk1p2
BOARD_USES_MMCUTILS := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_HAS_NO_SELECT_BUTTON := true
